### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by JonnyTech** [CuppaZee/CuppaZee#59]
The time displayed in the app is wrong. How can I set the correct timezone?

**Comment by sohcah** [comment]
Where? All dates/times in the app should be in your local Timezone, except for the top-right corner which intentionally displays the current time at Munzee HQ.

**Comment by JonnyTech** [comment]
Ah, yes, top right - very confusing!

![img_0](https://user-images.githubusercontent.com/3584732/88487754-c3250180-cf7f-11ea-96c1-0220d8270e3f.jpg)

Why is HQ time needed?
Can it be hidden or changed?

**Comment by sohcah** [comment]
HQ time is used by people to tell, for example, how long is left in the MHQ day, or to help with figuring out how long until something that munzee has announced it happening, as they always write times in MHQ time.

It basically just makes it easier to see what time it is at MHQ, rather than having to lookup where MHQ is and then lookup what time it is there.
