### ISSUE TITLE
Maintenance of the App

### ISSUE THREAD

**Issue by Sierra-Foxtrot** [CuppaZee/CuppaZee#7]
Since the last update of the app was long ago and I am missing 
* many of the new types that were added
* The category 'Seasonal Specials 2021' does not contain any of the 2021 events on Munzee

In there a chance that the app is maintained regularly?

**Comment by sohcah** [comment]
Updates to CuppaZee V1 are no longer able to be deployed due to an issue that is out of my control, and as such maintenance on it has stopped.

If you want the latest types, please use the CuppaZee V2 Beta (it is very stable), or CuppaZee Web (which already has V2).
https://www.facebook.com/CuppaZee/posts/1874592472691716

V2 is getting active maintenance, and various new features. My plan is to release V2 to everyone later this week.
